	subroutine MATMINOR(Q,R,K,IROW,ICOL,KQ1,KQ2,KR1,KR2)
c 06/17/90 09:17pm Lahey version of MINMAT
C MINORS OF A MATRIX.
C NOTE: Q AND R MUST BE DIFFERENT!
C SELECTS FROM Q THE K ROWS SPECIFIED BY IROW(1)..IROW(K)
C SELECTS FROM Q THE K COLS SPECIFIED BY ICOL(1)..ICOL(K)
C AND OUTPUTS THE RESULTING MATRIX IN R.
C KQ1 ETC=DECLARED DIMENSIONS
C
	REAL*8 Q(KQ1,KQ2),R(KR1,KR2)
	INTEGER ICOL(9),IROW(9)
C
c	TYPE 1,(IROW(I),I=1,K)
c1	FORMAT( ' IROW= ',7I4)
C
	DO 10 I=1,K
	DO 10 J=1,K
10	R(I,J)=Q(IROW(I),ICOL(J))
C
	RETURN
	END



