	subroutine RAC3(ROW,COL,amat,I1,I2,J1,J2,MAX,W,W1,
     &	KDR,KDC,KDA)
C RAC3 is version of RAC1 that uses AMAT rather than EM.EN
c
C SUBROUTINE TO CALC COEFFICIENTS W1(M) (REAL*8) AS
C ROW*A(M)*COL.
C RAC1 IS MORE ELABORATE VERSION OF RAC() THAT IS DESIGNED TO USE
C A SUBSECTION ONLY OF A(M), VIZ:
C   ROWS I1 TO I2 OF A(M) =NR ROWS, NR=I2-I1+1
C   COLS J1 TO J2 OF A(M) =NC COLUMNS, NC=J2-J1+1
C   MAX=SIZE OF A(M)=NUMBER OF W1() VALUES PRODUCED
C ASSUMES THAT ROW() IS 1XNR (I.E. USES 1ST NR ELEMENTS OF ROW())
C ASSUMES THAT COL() IS 1XNC (I.E. USES 1ST NC ELEMENTS OF COL())
C 	THE A(I,J,M) ARE SUPPLIED AS EM,EN.
C ALSO OUTPUTS REAL*4 VALUES IN W(M)
C   DECLARED DIMENSIONS IN CALLING PROG:
C	KDR FOR ROW(1,NR)
C	KDC FOR COL(NC,1)
C	KDA FOR EM(NA,NA),EN(NA,NA)
C
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	DIMENSION ROW(1,KDR),COL(KDC,1),AMAT(kda,kda,kda),W1(10)
	REAL*4 W(10)
C
	nR=i2-i1+1
	nC=j2-j1+1
C
	do 62 m=1,max
	W1(M)=0.0D0
	do 63 L=1,nR
	do 63 n=1,nC
	L1=L+i1-1	!=i1 to i2
	n1=n+j1-1	!=j1 to j2
63	W1(M)=W1(M)+row(1,L)*amat(L1,n1,m)*col(n,1)
	W(m)=SNGL(W1(m))
62	CONTINUE
	RETURN
	END
