


/*************************************************************************


		TITLE	:RIGID BODY MOTION
		AUTHOR	:IOAN LUISA VAIS
		COURSE	:MSC IN COMPUTER GRAPHICS
		MODULE	:ioLIB.H
		DATE	:01.05.1992

***************************************************************************


	CONTAINS:DECLARATIONS OF MIKE DAY PRIMITIVE DRAWING FUNCTIONS


***************************************************************************/
extern void iwpixel(int ,int ,int ,int ,int );
extern void linedraw(int x0, int y0, int x1, int y1, int colour);
extern void fill_circle(int xc, int yc, int radius, int colour);
extern void fill_poly(int [], int [], int n, int colour,int bcolor);

/*=========================================================================*/


		/*END OF MODULE ioLIB.H*/


/*=========================================================================*/
