	subroutine select_ouputs(ivalve,n_valve,ia0,ia1,ia2,ia3,ie)

	do i=1,n_valve

	enddo
	select case(ivalve)
		case(1)
			ia0= 1
			ia1= 0
			ia2= 0
			ia3= 0
			ie=  0
		case(2)
			ia0= 1
			ia1= 1
			ia2= 0
			ia3= 0
			ie=  0
		case(3)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(4)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(5)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(6)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(7)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(8)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(9)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(10)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(11)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(12)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(13)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(14)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(15)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(16)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(17)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(18)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(19)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(20)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(21)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(22)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(23)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(24)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
		case(25)
			ia0=
			ia1=
			ia2=
			ia3=
			ie=
	end select
	end
